#!/bin/sh

exec su -s /bin/sh -c "/usr/share/elasticsearch/bin/elasticsearch --default.path.conf=/etc/elasticsearch --default.path.data=/var/lib/elasticsearch --default.path.logs=/var/log/elasticsearch" elasticsearch
